### ISSUE TITLE
Potential error in TemporalFiltering (l. 1944) in HCP_helpers.py

### ISSUE THREAD

**Issue by tomosumi** [adolphslab/rsDenoise#2]
Thank you for providing great and very useful pytyon codes.
I found potential error in TemporalFiltering (l. 1944) in HCP_helpers.py, where data2.T should be x.T.

King regards,

**Comment by paola-g** [comment]
Hi Tomosumi,
you are correct - this was one of the latest addition to the code and it has not been tested for cifti files (my bad). Thanks for spotting it! I have now updated the code, if you can confirm that it now works properly I will close the issue.

**Comment by tomosumi** [comment]
Thank you for modifying the code.
I confirmed the change.
If I find other erros, I will tell you.
